### ISSUE TITLE
Support server side rendering

### ISSUE THREAD

**Issue by jean343** [georgeOsdDev/react-notification-badge#18]
There is a reference of window in the Animation Counter which breaks Meteor SSR.

Thanks

**Comment by georgeOsdDev** [comment]
https://github.com/chartjs/Chart.js/commit/da1d1ca5125b7fc6e90dd49b0656f3d82311e8e7

**Comment by georgeOsdDev** [comment]
@jean343 
I'v published v1.3.1 to npm.
https://www.npmjs.com/package/react-notification-badge
Please try latest one.

**Comment by jean343** [comment]
Thanks so much!
I will try tonight.

**Comment by jean343** [comment]
Sorry for the delay, it did work for me.
Thanks!
