### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead

### ISSUE THREAD

**Issue by GitShaffi** [georgeOsdDev/react-notification-badge#22]
Getting React.PropTypes deprecated warning with React latest 15.5.4 version.
Can we have react to be upgraded and use import PropTypes from 'prop-types' instead of React.PropTypes?

**Comment by georgeOsdDev** [comment]
#23 is merged

**Comment by georgeOsdDev** [comment]
@GitShaffi 
1.3.2 is now available
https://www.npmjs.com/package/react-notification-badge
