### ISSUE TITLE
There's a logical mistake in 'AnimationCounter.js' file!

### ISSUE THREAD

**Issue by mohsen89z** [georgeOsdDev/react-notification-badge#25]
in 'requestAnimationFrame' and 'cancelAnimationFrame' functions, your if statement is wrong!

**Comment by mohsen89z** [comment]
also when you're defining now variable,
you're checking if `'undefined' !== undefined` which is true always! you need to put the second 'undefined' inside a quotation.

**Comment by georgeOsdDev** [comment]
@mohsen89z 
Thanks!
https://github.com/georgeOsdDev/react-notification-badge/pull/26
