### ISSUE TITLE
React is peer dependency

### ISSUE THREAD

**Issue by ShockiTV** [georgeOsdDev/react-notification-badge#28]
Hi,
as React only 1 instance could be installed, your package was crashing our production as soon as badge was being instantiated.
We have to stay on "react": "~15.1.0", for now due to compatibility reasons and as your package have react as dependency, it pulls it's own version.
With peer dependency it will stay on the working 1.3.0 version or higher which does not need new react. But as there was no peer, it upgraded to new with its own bundled react.

Please link react and similar dependencies as peerDependency.

Regards
Robo

**Comment by georgeOsdDev** [comment]
@ShockiTV 

I updated `package.json` and v1.3.4 is released  on npm.
https://github.com/georgeOsdDev/react-notification-badge/commit/929590a9e95032c260194d1f6bebcf0d735c7f7c

Please try latest one.
