### ISSUE TITLE
Adding No Effect to Badge

### ISSUE THREAD

**Issue by amoghpalnitkar** [georgeOsdDev/react-notification-badge#30]
Hi,

Great work on the notification badge! I was wondering if there is anyway to specify no effect for the badge. I want to use this in the top header bar and would like no entry/exit effect on the badge.

Is that possible right now?
Thanks!

**Comment by georgeOsdDev** [comment]
You can use your custom `effect` prop without animation.

Ex:
myNoEffect: ['scale(1, 1)', 'scale(1, 1)'],

https://github.com/georgeOsdDev/react-notification-badge/blob/master/src/components/Effect.js

**Comment by georgeOsdDev** [comment]
I hope
`<NotificationBadge count={this.state.count} effect={[null, null, {}, {}]}/>`
will be result as you want.

https://github.com/georgeOsdDev/react-notification-badge/blob/master/example/app.js#L81

**Comment by amoghpalnitkar** [comment]
I obviously thought of adding a noEffect prop with no scaling. But, does it make sense to add a NO_EFFECT default in https://github.com/georgeOsdDev/react-notification-badge/blob/master/src/components/Effect.js itself. I can make a pull request for that.

Thanks!

**Comment by mtyeh411** [comment]
great component ... super simple to use ... just to chime in here ... my personal opinion is that it would be clearer if`NO_EFFECT` were the default
