### ISSUE TITLE
Error: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by anjdreas** [georgeOsdDev/react-notification-badge#5]
I followed the install instructions, although sourcing from a TypeScript file
`var NotificationBadge = require('react-notification-badge')`

and I'm getting the following error:
```
Error: Couldn't find preset "es2015" relative to directory "C:\\Repos\\foo\\node_modules\\react-notification-badge" while parsing file: C:\Repos\foo\node_modules\react-notification-badge\index.js
```

Any ideas? Other modules sourced the same way work just fine.

I'm transpiling TypeScript to javascript with browserify/watchify, using the following NPM task:

`watchify src/main.ts -v -t [ brfs ] -p [ tsify ] --debug -t babelify -x react -x react-dom -x react-router -x underscore -o scripts/bundle.js`

**Comment by georgeOsdDev** [comment]
Hi @anjdreas 

Please try this.
http://babeljs.io/docs/plugins/preset-es2015/

Sorry I'm not familliar to TypeScript,
But In my case, I create `package.json` like below. And it works fine.

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "watchify index.js -o main.js -dv",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-notification-badge": "^1.0.0"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babelify": "^7.2.0",
    "browserify": "^12.0.1",
    "watchify": "^3.6.1"
  },
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "compact": false,
          "presets": [
            "react",
            "es2015"
          ]
        }
      ]
    ]
  }
}
```

**Comment by anjdreas** [comment]
Thanks, I'll give it a try.

**Comment by georgeOsdDev** [comment]
Hi @anjdreas
I also pushed transpiled code from v1.1.0.
Please try it.
